apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    role: api
  ports:
    - port: {{ .Values.backend.service.port }}
      protocol: TCP

