apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.mongodb.service.type }}
  selector:
    app: mongodb
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.containerPort }}
      protocol: TCP

