apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.secret.name }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  username: {{ .Values.mongodb.secret.username | b64enc }}
  password: {{ .Values.mongodb.secret.password | b64enc }}

